### ISSUE TITLE
No 'boost' attribute.

### ISSUE THREAD

**Issue by impshum** [acidvegas/chir.py#1]
Running on MacOSX 
Installed Tweepy and Feedparser
Just forked today.

Here's what happened.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/impshum/Sites/Github/chir.py/chir.py/twitter.py", line 45, in run
    boost_tweet = api.update_status('Support our Twitter! #' + ' #'.join(config.boost))
AttributeError: module 'config' has no attribute 'boost'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/impshum/Sites/Github/chir.py/chir.py/twitter.py", line 50, in run
    random.shuffle(config.boost)
AttributeError: module 'config' has no attribute 'boost'

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/impshum/Sites/Github/chir.py/chir.py/twitter.py", line 129, in run
    query_keywords = query_keywords + config.boost_keywords
TypeError: can only concatenate list (not "tuple") to list
```

**Comment by acidvegas** [comment]
Ah, should be config.boost_keywords instead of config.boost
This project is old and unmaintained, though I will push a fix for you!
